---
# Agents variables

# Config
xcode: True
android_ndk: False
macos_update_recommended_only: True

# Versions
android_build_tools: 28.0.3
xcode_version: 10.3
xcode_major_version: 10
appc_cli_node: 8
nvm_version: 0.34.0

# Path
android_sdk_path: /usr/local/share/android-sdk
android_ndk_path: /usr/local/share/android-ndk
xcode_xpi_path: "{{ ansible_env.HOME }}/Downloads/Xcode_{{ xcode_version }}.xip"

# Other variables
locale: en_GB